/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as postsPostsIndexRouteImport } from './routes/(posts)/posts/index'
import { Route as postsPostsPostIdRouteImport } from './routes/(posts)/posts/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const postsPostsIndexRoute = postsPostsIndexRouteImport.update({
  id: '/(posts)/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const postsPostsPostIdRoute = postsPostsPostIdRouteImport.update({
  id: '/(posts)/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postId': typeof postsPostsPostIdRoute
  '/posts/': typeof postsPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof postsPostsPostIdRoute
  '/posts': typeof postsPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(posts)/posts/$postId': typeof postsPostsPostIdRoute
  '/(posts)/posts/': typeof postsPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$postId' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postId' | '/posts'
  id: '__root__' | '/' | '/(posts)/posts/$postId' | '/(posts)/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  postsPostsPostIdRoute: typeof postsPostsPostIdRoute
  postsPostsIndexRoute: typeof postsPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(posts)/posts/': {
      id: '/(posts)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof postsPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(posts)/posts/$postId': {
      id: '/(posts)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof postsPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  postsPostsPostIdRoute: postsPostsPostIdRoute,
  postsPostsIndexRoute: postsPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
