/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as postPostsIndexRouteImport } from './routes/(post)/posts/index'
import { Route as postPostsPostIdRouteImport } from './routes/(post)/posts/$postId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const postPostsIndexRoute = postPostsIndexRouteImport.update({
  id: '/(post)/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const postPostsPostIdRoute = postPostsPostIdRouteImport.update({
  id: '/(post)/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postId': typeof postPostsPostIdRoute
  '/posts/': typeof postPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof postPostsPostIdRoute
  '/posts': typeof postPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(post)/posts/$postId': typeof postPostsPostIdRoute
  '/(post)/posts/': typeof postPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/posts/$postId' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postId' | '/posts'
  id: '__root__' | '/' | '/(post)/posts/$postId' | '/(post)/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  postPostsPostIdRoute: typeof postPostsPostIdRoute
  postPostsIndexRoute: typeof postPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(post)/posts/': {
      id: '/(post)/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof postPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(post)/posts/$postId': {
      id: '/(post)/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof postPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  postPostsPostIdRoute: postPostsPostIdRoute,
  postPostsIndexRoute: postPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
